const invoke = window.__TAURI__?.core?.invoke;
const listen = window.__TAURI__?.event?.listen;

const demoState = {
  devices:[{id:'usb-1b1c-2b32-demo',vendorId:'1b1c',productId:'2b32',name:'CORSAIR IRONCLAW WIRELESS SE Gaming Mouse',serial:'DEMO-IRONCLAW-001',transport:'usb',connected:true,protocolSupported:false,inputNodes:[]}],
  buttons:[['mouse1','Left click','BTN_LEFT'],['mouse2','Right click','BTN_RIGHT'],['mouse3','Wheel click','BTN_MIDDLE'],['wheelup','Wheel up','REL_WHEEL_UP'],['wheeldn','Wheel down','REL_WHEEL_DOWN'],['dpiup','DPI up','LEARN'],['dpidn','DPI down','LEARN'],['profup','Profile up','LEARN'],['profdn','Profile down','LEARN'],['forward','Forward','BTN_FORWARD'],['back','Back','BTN_BACK'],['option','Option','LEARN']].map(([id,name,source])=>({id,name,source})),
  driver:{running:false,permissionRequired:false,inputNodes:[],error:'Development preview: native input engine is not attached',learnButton:'',lastCapture:null,activeSources:[]},
  rgb:{available:false,backend:'',deviceName:'',reason:'Checking OpenRGB for a compatible Ironclaw controller…',lastApplied:null},
  config:{version:1,activeProfile:'desktop',profiles:[{id:'desktop',name:'Desktop',accent:'#38d9c5',dpiStages:[800,1600,3200],activeDpi:1,pollingRate:1000,lighting:{mode:'static',color:'#38d9c5',secondaryColor:'#ff6b35',brightness:72,speed:45,zones:{logo:true,wheel:true,front:true}},mappings:{mouse1:{action:'passthrough',value:'BTN_LEFT',label:'Left click'},mouse2:{action:'passthrough',value:'BTN_RIGHT',label:'Right click'},mouse3:{action:'passthrough',value:'BTN_MIDDLE',label:'Wheel click'},wheelup:{action:'passthrough',value:'REL_WHEEL_UP',label:'Scroll up'},wheeldn:{action:'passthrough',value:'REL_WHEEL_DOWN',label:'Scroll down'},dpiup:{action:'dpi',value:'next',label:'Next DPI'},dpidn:{action:'dpi',value:'previous',label:'Previous DPI'},profup:{action:'profile',value:'next',label:'Next profile'},profdn:{action:'profile',value:'previous',label:'Previous profile'},forward:{action:'passthrough',value:'BTN_FORWARD',label:'Forward'},back:{action:'passthrough',value:'BTN_BACK',label:'Back'},option:{action:'shortcut',value:'CTRL+ALT+T',label:'Open terminal'}},sources:{mouse1:'EV_KEY:272',mouse2:'EV_KEY:273',mouse3:'EV_KEY:274',wheelup:'EV_REL:8:1',wheeldn:'EV_REL:8:-1',forward:'EV_KEY:277',back:'EV_KEY:278'}}]}
};

let state, workingProfile, selectedButton='mouse1', dirty=false, polling, recordingShortcut=false;
const liveSources=new Set(), polledSources=new Set(), releaseTimers=new Map();
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const clone=value=>JSON.parse(JSON.stringify(value));

async function call(command,args={}){if(!invoke)throw new Error('Native bridge unavailable in preview');return invoke(command,args)}
function activeProfile(){return state.config.profiles.find(p=>p.id===state.config.activeProfile)||state.config.profiles[0]}
function buttonDef(id){return state.buttons.find(b=>b.id===id)||{id,name:id,source:'LEARN'}}
function humanAction(mapping){return mapping.label||mapping.value||mapping.action}
function markDirty(){dirty=true;$('#dirty-indicator').textContent='UNSAVED CHANGES';$('#dirty-indicator').classList.add('dirty')}
function toast(message,error=false){const el=$('#toast');el.querySelector('p').textContent=message;el.classList.toggle('error',error);el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2600)}

function renderDevice(){const device=state.devices[0];const connected=!!device;$('#title-device-name').textContent=device?.name||'No Corsair device';$('#title-device-id').textContent=device?`${device.vendorId}:${device.productId}`.toUpperCase():'—';$('.title-device .signal').classList.toggle('online',connected);$('#rail-device-name').textContent=device?.name.replace(/^CORSAIR /i,'')||'No device';$('#rail-device-transport').textContent=connected?`${device.transport} / connected`.toUpperCase():'DISCONNECTED';$('#usb-id').textContent=device?`${device.vendorId}:${device.productId}`.toUpperCase():'—';$('#usb-input').textContent=device?.inputNodes?.length?`${device.inputNodes.length} EVENT NODES`:'RECONNECT AFTER INSTALL';$('#usb-card').classList.toggle('connected',connected)}
function renderProfiles(){const list=$('#profile-list');list.innerHTML='';state.config.profiles.forEach(profile=>{const button=document.createElement('button');button.className=`profile-item ${profile.id===state.config.activeProfile?'active':''}`;button.style.setProperty('--profile-color',profile.accent);button.innerHTML=`<i></i><b>${escapeHtml(profile.name)}</b><span>${profile.id===state.config.activeProfile?'LIVE':'··'}</span>`;button.onclick=()=>activateProfile(profile.id);list.append(button)})}
function renderDriver(){const d=state.driver;const root=$('#driver-health');root.classList.toggle('ok',d.running);root.classList.toggle('error',!!d.error&&!d.running);$('#driver-label').textContent=d.running?`${d.inputNodes.length} nodes / running`:d.permissionRequired?'Permission required':d.error||'Not started';$('#driver-details').textContent=JSON.stringify(d,null,2)}
function renderRgb(){const rgb=state.rgb;$('#rgb-nav-state').textContent=rgb.available?'LIVE':'LOCK';const banner=$('#rgb-banner');banner.classList.toggle('available',rgb.available);banner.querySelector('span').textContent=rgb.available?'✓':'!';banner.querySelector('b').textContent=rgb.available?`${rgb.backend.toUpperCase()} READY`:'RGB LOCKED FOR DEVICE SAFETY';banner.querySelector('p').textContent=rgb.available?`Detected ${rgb.deviceName}`:rgb.reason;$('#apply-lighting').disabled=!rgb.available}

function renderAssignments(){const map=workingProfile.mappings;$$('.hotspots [data-button]').forEach(el=>el.classList.toggle('active',el.dataset.button===selectedButton));const def=buttonDef(selectedButton),mapping=map[selectedButton];$('#editor-index').textContent=String(state.buttons.findIndex(b=>b.id===selectedButton)+1).padStart(2,'0');$('#selected-button-name').textContent=def.name;$('#selected-source').textContent=workingProfile.sources[selectedButton]||'UNIDENTIFIED — USE IDENTIFY INPUT';renderActionEditor(mapping);const list=$('#mapping-list');list.innerHTML='';state.buttons.forEach((button,index)=>{const row=document.createElement('div');row.className='mapping-row';row.dataset.button=button.id;row.innerHTML=`<span>${String(index+1).padStart(2,'0')}</span><b>${escapeHtml(button.name)}</b><em>${escapeHtml(humanAction(map[button.id]))}</em>`;row.onclick=()=>{selectedButton=button.id;renderAssignments()};list.append(row)});renderLiveInputs()}
function buttonIdsForSource(source){const ids=Object.entries(workingProfile.sources).filter(([,candidate])=>candidate===source).map(([id])=>id);if(ids.length)return ids;return {"EV_KEY:272":["mouse1"],"EV_KEY:273":["mouse2"],"EV_KEY:274":["mouse3"],"EV_KEY:275":["back"],"EV_KEY:276":["forward"],"EV_KEY:277":["forward"],"EV_KEY:278":["back"],"EV_REL:8:1":["wheelup"],"EV_REL:8:-1":["wheeldn"]}[source]||[]}
function renderLiveInputs(){const sources=new Set([...liveSources,...polledSources]);const activeButtons=new Set([...sources].flatMap(buttonIdsForSource));$$('[data-button]').forEach(el=>el.classList.toggle('pressed',activeButtons.has(el.dataset.button)));const status=$('#physical-status');status.classList.toggle('physical',sources.size>0)}
function handlePhysicalInput(input){if(!input?.source)return;clearTimeout(releaseTimers.get(input.source));const release=()=>{liveSources.delete(input.source);releaseTimers.delete(input.source);renderLiveInputs()};if(input.pressed){liveSources.add(input.source);$('#physical-status span').textContent=`PHYSICAL INPUT / ${input.source}`;renderLiveInputs();const preview=$('.light-preview');if(workingProfile?.lighting?.mode==='reactive'){preview.classList.remove('reactive-hit');requestAnimationFrame(()=>preview.classList.add('reactive-hit'));clearTimeout(preview.reactiveTimer);preview.reactiveTimer=setTimeout(()=>preview.classList.remove('reactive-hit'),430)}if(input.pulse)releaseTimers.set(input.source,setTimeout(release,160))}else{releaseTimers.set(input.source,setTimeout(release,160))}}
const choice=(value,label=value)=>({value,label});
const actionDetails={passthrough:['Keep the mouse button’s original behaviour.','No additional value is needed; the original input passes through unchanged.'],shortcut:['Send several keyboard keys together.','Choose Record Shortcut, then press the complete combination.'],key:['Replace this control with one keyboard key.','Choose the key the mouse button should produce.'],media:['Control audio, playback, or a common desktop function.','Choose a media or system command.'],dpi:['Move through this profile’s DPI stages.','Choose which direction to move through the sensitivity stages.'],profile:['Change the active mouse profile.','Choose which direction to move through saved profiles.'],disabled:['Capture the button without producing output.','No additional value is needed; this physical input is discarded.']};
function actionValueGroups(action){if(action==='key')return [{label:'Common keys',items:[choice('ENTER','Enter'),choice('SPACE','Space'),choice('TAB','Tab'),choice('ESC','Escape'),choice('BACKSPACE','Backspace'),choice('DELETE','Delete'),choice('CAPSLOCK','Caps Lock')]},{label:'Navigation',items:[choice('UP','Arrow Up'),choice('DOWN','Arrow Down'),choice('LEFT','Arrow Left'),choice('RIGHT','Arrow Right'),choice('HOME','Home'),choice('END','End'),choice('PAGEUP','Page Up'),choice('PAGEDOWN','Page Down'),choice('INSERT','Insert')]},{label:'Function keys',items:Array.from({length:24},(_,index)=>choice(`F${index+1}`))},{label:'Letters',items:[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(value=>choice(value))},{label:'Numbers',items:[...'0123456789'].map(value=>choice(value))},{label:'Modifiers',items:[choice('CTRL','Control'),choice('ALT','Alt'),choice('SHIFT','Shift'),choice('META','Super / Meta')]}];if(action==='media')return [{label:'Playback',items:[choice('PLAYPAUSE','Play / Pause'),choice('PREVIOUSSONG','Previous Track'),choice('NEXTSONG','Next Track'),choice('STOP','Stop Playback')]},{label:'Volume',items:[choice('MUTE','Mute'),choice('VOLUMEDOWN','Volume Down'),choice('VOLUMEUP','Volume Up')]},{label:'Desktop',items:[choice('CALC','Calculator'),choice('MAIL','Mail'),choice('BACK','Back'),choice('FORWARD','Forward')]}];if(action==='dpi')return [{label:'DPI direction',items:[choice('next','Next DPI Stage'),choice('previous','Previous DPI Stage')]}];if(action==='profile')return [{label:'Profile direction',items:[choice('next','Next Profile'),choice('previous','Previous Profile')]}];return []}
function renderValueChoices(mapping){const select=$('#action-value'),groups=actionValueGroups(mapping.action),labels={key:'KEY',media:'MEDIA / SYSTEM COMMAND',dpi:'DIRECTION',profile:'DIRECTION'};$('#action-value-label').textContent=labels[mapping.action]||'ACTION VALUE';select.replaceChildren();const known=new Set();groups.forEach(group=>{const optgroup=document.createElement('optgroup');optgroup.label=group.label;group.items.forEach(item=>{known.add(item.value);const option=document.createElement('option');option.value=item.value;option.textContent=item.label;optgroup.append(option)});select.append(optgroup)});if(mapping.value&&!known.has(mapping.value)){const saved=document.createElement('optgroup');saved.label='Saved value';const option=document.createElement('option');option.value=mapping.value;option.textContent=`${mapping.value} (legacy)`;saved.append(option);select.prepend(saved)}select.value=mapping.value}
function updateActionHint(){const detail=actionDetails[$('#action-type').value]||['Configure this action.',''];$('#action-selection-copy').textContent=detail[0];$('#action-hint').textContent=detail[1]}
function renderActionEditor(mapping){$('#action-type').value=mapping.action;const shortcut=mapping.action==='shortcut',hasChoices=['key','media','dpi','profile'].includes(mapping.action);$('#shortcut-editor').hidden=!shortcut;$('#value-editor').hidden=!hasChoices;if(hasChoices)renderValueChoices(mapping);setShortcutRecording(false);renderShortcutPreview(mapping.value);updateActionHint()}
function shortcutTokens(value=''){return value.split('+').map(token=>token.trim()).filter(Boolean)}
function readableKey(token){return {CTRL:'Control',ALT:'Alt',SHIFT:'Shift',META:'Super',ESC:'Escape',SPACE:'Space',ENTER:'Enter',TAB:'Tab'}[token]||token}
function renderShortcutPreview(value='',waiting=false){const preview=$('#shortcut-preview');preview.replaceChildren();const tokens=shortcutTokens(value);if(!tokens.length){const idle=document.createElement('span');idle.className='shortcut-idle';idle.textContent=waiting?'PRESS YOUR KEYS…':'NO SHORTCUT RECORDED';preview.append(idle)}else tokens.forEach((token,index)=>{if(index){const plus=document.createElement('b');plus.textContent='+';preview.append(plus)}const key=document.createElement('kbd');key.textContent=token;preview.append(key)});$('#shortcut-readable').textContent=tokens.length?`Preview: pressing this mouse button sends ${tokens.map(readableKey).join(' + ')}.`:waiting?'Listening now — hold modifiers and press the final key.':'Choose Record Shortcut, then press your key combination.'}
function setShortcutRecording(active){recordingShortcut=active;const button=$('#record-shortcut'),preview=$('#shortcut-preview');button.classList.toggle('recording',active);preview.classList.toggle('recording',active);button.querySelector('span').textContent=active?'PRESS KEYS…':'RECORD SHORTCUT';if(active){renderShortcutPreview('',true);preview.focus()}}
function normalizedKey(key){const names={Control:'CTRL',Alt:'ALT',Shift:'SHIFT',Meta:'META',' ':'SPACE',Escape:'ESC',ArrowUp:'UP',ArrowDown:'DOWN',ArrowLeft:'LEFT',ArrowRight:'RIGHT',PageUp:'PAGEUP',PageDown:'PAGEDOWN'};return names[key]||(key.length===1?key.toUpperCase():key.toUpperCase().replaceAll(' ',''))}
function recordShortcutKey(event){if(!recordingShortcut||$('#action-type').value!=='shortcut')return;event.preventDefault();event.stopPropagation();if(event.key==='Escape'){setShortcutRecording(false);renderShortcutPreview(workingProfile.mappings[selectedButton].value);toast('Shortcut recording cancelled');return}const keys=[];if(event.ctrlKey)keys.push('CTRL');if(event.altKey)keys.push('ALT');if(event.shiftKey)keys.push('SHIFT');if(event.metaKey)keys.push('META');const modifier=['Control','Alt','Shift','Meta'].includes(event.key);if(!modifier)keys.push(normalizedKey(event.key));const shortcut=[...new Set(keys)].join('+');renderShortcutPreview(shortcut,true);if(modifier)return;const mapping=workingProfile.mappings[selectedButton];mapping.value=shortcut;mapping.label=shortcut;setShortcutRecording(false);renderAssignments();markDirty();toast(`Shortcut recorded: ${shortcut}`)}
function renderLighting(){const l=workingProfile.lighting;if(l.mode==='rainbow')l.mode='spectrum';$$('#effect-options button').forEach(b=>b.classList.toggle('active',b.dataset.mode===l.mode));$('#primary-color').value=l.color;$('#secondary-color').value=l.secondaryColor;$('#brightness').value=l.brightness;$('#speed').value=l.speed;setRange($('#brightness'),l.brightness);setRange($('#speed'),l.speed);const preview=$('.light-preview'),duration=Math.max(.65,5.5-(l.speed/100)*4.5);preview.dataset.effect=l.mode;preview.style.setProperty('--primary',l.color);preview.style.setProperty('--secondary',l.secondaryColor);preview.style.setProperty('--light-level',String(Math.max(.05,l.brightness/100)));preview.style.setProperty('--effect-duration',`${duration}s`);$('#lighting-preview-label').textContent=`${l.mode.toUpperCase()} / LIVE PREVIEW`;$$('[data-zone]').forEach(input=>input.checked=l.zones[input.dataset.zone]!==false);$$('[data-light-zone]').forEach(zone=>zone.classList.toggle('zone-off',l.zones[zone.dataset.lightZone]===false))}
function renderPerformance(){const p=workingProfile;const dpi=p.dpiStages[p.activeDpi];$('#dpi-readout').textContent=dpi;$('#dpi-nav-state').textContent=dpi;const root=$('#dpi-stages');root.innerHTML='';p.dpiStages.forEach((value,index)=>{const row=document.createElement('label');row.className='dpi-stage';row.innerHTML=`<span>${String(index+1).padStart(2,'0')}</span><input type="number" min="100" max="26000" step="100" value="${value}"><small>DPI</small><input type="radio" name="active-dpi" ${index===p.activeDpi?'checked':''}>`;row.querySelector('input[type=number]').onchange=e=>{p.dpiStages[index]=Math.max(100,Math.min(26000,Number(e.target.value)||800));renderPerformance();markDirty()};row.querySelector('input[type=radio]').onchange=()=>{p.activeDpi=index;renderPerformance();markDirty()};root.append(row)});$$('#poll-options button').forEach(b=>b.classList.toggle('active',Number(b.dataset.rate)===p.pollingRate))}
function renderAll(){workingProfile=clone(activeProfile());renderDevice();renderProfiles();renderDriver();renderRgb();renderAssignments();renderLighting();renderPerformance()}
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setRange(input,value){input.style.setProperty('--range',`${value}%`);$(`#${input.id}-value`).textContent=`${value}%`}

async function activateProfile(id){if(dirty&&!confirm('Discard unsaved changes?'))return;try{if(invoke)await call('activate_profile',{profileId:id});state.config.activeProfile=id;dirty=false;$('#dirty-indicator').classList.remove('dirty');$('#dirty-indicator').textContent='ALL CHANGES SAVED';renderAll()}catch(error){toast(String(error),true)}}
async function save(){try{await call('save_profile',{profile:workingProfile});const index=state.config.profiles.findIndex(p=>p.id===workingProfile.id);state.config.profiles[index]=clone(workingProfile);dirty=false;$('#dirty-indicator').classList.remove('dirty');$('#dirty-indicator').textContent='ALL CHANGES SAVED';renderProfiles();toast('Profile saved to disk')}catch(error){if(!invoke){toast('Preview mode — native save unavailable',true)}else toast(String(error),true)}}
async function rescan(){try{if(invoke)state.devices=await call('rescan_devices');const fresh=await call('get_state');state.rgb=fresh.rgb;renderDevice();renderRgb();toast(state.devices.length?'Device scan complete':'No Corsair device detected')}catch(error){toast(String(error),true)}}
async function pollState(){
  if(!invoke)return;
  try{
    const fresh=await call('get_state');
    state.driver=fresh.driver;
    state.rgb=fresh.rgb;
    let internalStateChanged=false;
    if(!dirty){
      const oldProfile=state.config.profiles.find(profile=>profile.id===state.config.activeProfile);
      const newProfile=fresh.config.profiles.find(profile=>profile.id===fresh.config.activeProfile);
      internalStateChanged=state.config.activeProfile!==fresh.config.activeProfile||oldProfile?.activeDpi!==newProfile?.activeDpi;
      state.config=fresh.config;
      if(internalStateChanged){workingProfile=clone(activeProfile());renderProfiles();renderAssignments();renderPerformance()}
    }
    let mappingChanged=false;
    if(fresh.driver.lastCapture){
      const capture=fresh.driver.lastCapture;
      if(capture.buttonId&&workingProfile.sources[capture.buttonId]!==capture.source){
        workingProfile.sources[capture.buttonId]=capture.source;
        selectedButton=capture.buttonId;
        mappingChanged=true;
        markDirty();
        toast(`Input identified: ${capture.source}`)
      }
    }
    renderDriver();renderRgb();
    polledSources.clear();
    (fresh.driver.activeSources||[]).forEach(source=>polledSources.add(source));
    if(mappingChanged)renderAssignments();else renderLiveInputs();
    $('#learn-button').classList.toggle('listening',!!fresh.driver.learnButton);
    $('#learn-button').innerHTML=fresh.driver.learnButton?'<span>●</span> PRESS A MOUSE BUTTON':'<span>◎</span> IDENTIFY INPUT'
  }catch{}
}

function bindEvents(){
  $$('.nav-item').forEach(button=>button.onclick=()=>{$$('.nav-item').forEach(b=>b.classList.remove('active'));button.classList.add('active');$$('.panel').forEach(p=>p.classList.remove('active'));$(`#panel-${button.dataset.panel}`).classList.add('active')});
  const selectDiagramButton=button=>{if(!button||button.dataset.button===selectedButton)return;selectedButton=button.dataset.button;renderAssignments()};
  $('.mouse-blueprint').onpointerdown=e=>{const button=e.target.closest?.('.hotspots [data-button]');if(!button)return;e.preventDefault();selectDiagramButton(button)};
  $$('.hotspots [data-button]').forEach(button=>{button.onclick=()=>selectDiagramButton(button);button.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectDiagramButton(button)}}});
  $('#action-type').onchange=e=>{const m=workingProfile.mappings[selectedButton];m.action=e.target.value;const defaults={passthrough:buttonDef(selectedButton).source,shortcut:'CTRL+ALT+T',key:'F13',media:'PLAYPAUSE',dpi:'next',profile:'next',disabled:''};m.value=defaults[m.action];m.label=m.action==='disabled'?'Disabled':m.value;renderAssignments();markDirty();if(m.action==='shortcut')toast('Shortcut recorder ready')};
  $('#action-value').onchange=e=>{const m=workingProfile.mappings[selectedButton],option=e.target.selectedOptions[0];m.value=e.target.value;m.label=option?.textContent||m.value;renderAssignments();markDirty()};
  $('#record-shortcut').onclick=()=>{if(recordingShortcut){setShortcutRecording(false);renderShortcutPreview(workingProfile.mappings[selectedButton].value)}else setShortcutRecording(true)};
  $('#shortcut-preview').onclick=()=>{if(!recordingShortcut)setShortcutRecording(true)};
  $('#shortcut-preview').onkeydown=recordShortcutKey;
  $$('.quick-actions button').forEach(button=>button.onclick=()=>{const m=workingProfile.mappings[selectedButton];m.action=button.dataset.quick.includes('+')?'shortcut':'media';m.value=button.dataset.quick;m.label=button.textContent.trim();renderAssignments();markDirty()});
  $('#learn-button').onclick=async()=>{try{await call('learn_button',{buttonId:selectedButton});$('#learn-button').classList.add('listening');$('#learn-button').innerHTML='<span>●</span> PRESS A MOUSE BUTTON'}catch(error){toast(String(error),true)}};
  $('#save-profile').onclick=save;$$('.save-alias').forEach(b=>b.onclick=save);
  $('#rescan').onclick=rescan;$('#rescan-main').onclick=rescan;
  $('#new-profile').onclick=async()=>{const name=prompt('Profile name');if(!name)return;const profile=clone(workingProfile);profile.name=name.trim().slice(0,40);profile.id=profile.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,32)||`profile-${Date.now()}`;try{await call('create_profile',{profile});state.config.profiles.push(profile);await activateProfile(profile.id);toast('Profile created')}catch(error){toast(String(error),true)}};
  $$('#effect-options button').forEach(button=>button.onclick=()=>{workingProfile.lighting.mode=button.dataset.mode;renderLighting();markDirty()});
  $('#primary-color').oninput=e=>{workingProfile.lighting.color=e.target.value;renderLighting();markDirty()};$('#secondary-color').oninput=e=>{workingProfile.lighting.secondaryColor=e.target.value;renderLighting();markDirty()};
  ['brightness','speed'].forEach(id=>{$(`#${id}`).oninput=e=>{workingProfile.lighting[id]=Number(e.target.value);renderLighting();markDirty()}});
  $$('[data-zone]').forEach(input=>input.onchange=e=>{workingProfile.lighting.zones[e.target.dataset.zone]=e.target.checked;renderLighting();markDirty()});
  $('#apply-lighting').onclick=async()=>{try{await save();await call('apply_rgb');toast('Lighting applied to device')}catch(error){toast(String(error),true)}};
  $('#add-dpi').onclick=()=>{if(workingProfile.dpiStages.length>=6)return toast('Maximum six DPI stages',true);const last=workingProfile.dpiStages.at(-1)||800;workingProfile.dpiStages.push(Math.min(26000,last*2));renderPerformance();markDirty()};
  $$('#poll-options button').forEach(button=>button.onclick=()=>{workingProfile.pollingRate=Number(button.dataset.rate);renderPerformance();markDirty()});
  $('#driver-info').onclick=()=>$('#info-dialog').showModal();$('.dialog-close').onclick=()=>$('#info-dialog').close();
  $('.titlebar').onmousedown=e=>{if(e.button!==0||e.target.closest('.window-controls,button,input,select,a'))return;call('window_start_drag').catch(()=>{})};
  $('#window-minimize').onclick=()=>call('window_minimize').catch(()=>{});$('#window-maximize').onclick=()=>call('window_toggle_maximize').catch(()=>{});$('#window-close').onclick=()=>call('window_close').catch(()=>{});
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
}

async function init(){try{state=await call('get_state')}catch{state=clone(demoState)}renderAll();bindEvents();polling=setInterval(pollState,100);pollState();if(listen)listen('physical-input',event=>handlePhysicalInput(event.payload)).catch(()=>{})}
init();
